"""Bit-equality (or tight-atol) regression tests against the golden reference.

The golden reference (``tests/golden_reference/*.npz``) was generated by
``tests/build_golden_reference.py`` on the Phase-0 code path. Every later
optimization phase must reproduce these arrays.

Phase 1 (incremental heights) is expected to be **bit-equal** (atol=0)
because the population standard-deviation formula is the same, just
computed via ``np.std`` instead of a Python for-loop.

Phase 4 (numba kernel) is expected to **diverge** because the random
number generator changes (``random.randint`` → numba-compatible
``np.random``). For Phase 4, this test should be parameterized with a
looser ``atol`` and a statistical-equivalence test should be added
separately.

Performance note: each simulation run is cached via ``lru_cache``
(a single cell runs ONCE and is reused across the fluctuation +
avg_height tests). The largest L=200 cells are marked ``slow`` and
skipped by default — invoke ``pytest -m slow`` (or remove the
``-m 'not slow'`` filter) to include them.
"""

from __future__ import annotations

from functools import lru_cache

import numpy as np
import pytest

from tests.build_golden_reference import build_density_for_piece_19_combined
from tetris_ballistic.tetris_ballistic import Tetris_Ballistic

RATIO = 2


@lru_cache(maxsize=None)
def _run_one(pct: int, L: int, seed: int):
    density = build_density_for_piece_19_combined(pct)
    height = L * RATIO
    steps = RATIO * L * L
    tb = Tetris_Ballistic(
        width=L, height=height, steps=steps, seed=seed, density=density
    )
    tb.Simulate()
    n = int(tb.FinalSteps)
    return (
        tb.Fluctuation[:n].astype(np.float64).copy(),
        tb.AvergeHeight[:n].astype(np.float64).copy(),
        n,
    )


def _maybe_skip_slow(L: int):
    if L >= 200:
        pytest.skip(f"L={L} marked slow — run with -m 'slow' to include")


def test_fluctuation_matches_golden(golden_cell):
    _maybe_skip_slow(golden_cell["L"])
    fluct, _, n = _run_one(golden_cell["pct"], golden_cell["L"], golden_cell["seed"])
    assert n == golden_cell["final_steps"], (
        f"FinalSteps mismatch: got {n}, expected {golden_cell['final_steps']}"
    )
    # Tolerance rationale: the legacy Fluctuation formula
    #   sqrt( sum((h_i - mean)^2) / W )
    # is the *population* standard deviation (divisor W). Phase 1 uses
    # np.std(heights), which is the same population std but with a
    # different summation order, so results differ at FP roundoff
    # (~1e-15 absolute). 1e-12 is a safety margin still 4 orders of
    # magnitude tighter than the smallest physically meaningful scale.
    np.testing.assert_allclose(
        fluct, golden_cell["fluctuation"],
        atol=1e-12, rtol=1e-12,
        err_msg=f"Fluctuation diverged for pct={golden_cell['pct']} "
                f"L={golden_cell['L']} seed={golden_cell['seed']}",
    )


def test_avg_height_matches_golden(golden_cell):
    _maybe_skip_slow(golden_cell["L"])
    _, avg, n = _run_one(golden_cell["pct"], golden_cell["L"], golden_cell["seed"])
    assert n == golden_cell["final_steps"]
    np.testing.assert_allclose(
        avg, golden_cell["avg_height"],
        atol=0.0, rtol=0.0,
        err_msg=f"AvergeHeight diverged for pct={golden_cell['pct']} "
                f"L={golden_cell['L']} seed={golden_cell['seed']}",
    )


@pytest.mark.slow
def test_slow_L200_matches_golden(golden_dir):
    """Full coverage including the largest L=200 cells. Skipped by default."""
    for seed in (0, 10, 20):
        path = golden_dir / f"pct50_L200_seed{seed}.npz"
        if not path.exists():
            pytest.skip(f"{path.name} not built")
        data = np.load(path)
        fluct, avg, n = _run_one(50, 200, seed)
        assert n == int(data["final_steps"])
        np.testing.assert_allclose(fluct, data["fluctuation"], atol=1e-12, rtol=1e-12)
        np.testing.assert_allclose(avg, data["avg_height"], atol=0.0, rtol=0.0)
