width: 10
height: 42
steps: 90
seed: -2
Piece-0:  [4,  1]
Piece-1:  [4,  1]
Piece-2:  [2,  1]
Piece-3:  [11, 1]
Piece-4:  [1,  1]
Piece-5:  [1,  1]
Piece-6:  [1,  1]
Piece-7:  [11, 1]
Piece-8:  [1,  1]
Piece-9:  [1,  1]
Piece-10: [1,  1]
Piece-11: [11, 1]
Piece-12: [1,  1]
Piece-13: [2,  1]
Piece-14: [1,  1]
Piece-15: [11, 1]
Piece-16: [1,  1]
Piece-17: [1,  1]
Piece-18: [1,  1]
Piece-19: [0,  0]
