steps: 12000
width: 100
height: 300
seed: 12
Piece-0: [0, 0]
Piece-1: [0, 0]
Piece-2: [0, 0]
Piece-3: [0, 0]
Piece-4: [0, 0]
Piece-5: [0, 0]
Piece-6: [0, 0]
Piece-7: [0, 0]
Piece-8: [0, 0]
Piece-9: [0, 0]
Piece-10: [0, 0]
Piece-11: [0, 0]
Piece-12: [1, 0]
Piece-13: [0, 0]
Piece-14: [0, 0]
Piece-15: [0, 0]
Piece-16: [0, 0]
Piece-17: [0, 0]
Piece-18: [0, 0]
Piece-19: [0, 0]
