steps: 12000
width: 100
height: 300
seed: 12
Piece-0: [1, 1]
Piece-1: [1, 1]
Piece-2: [1, 1]
Piece-3: [1, 1]
Piece-4: [1, 1]
Piece-5: [1, 1]
Piece-6: [1, 1]
Piece-7: [1, 1]
Piece-8: [1, 1]
Piece-9: [1, 1]
Piece-10: [1, 1]
Piece-11: [1, 1]
Piece-12: [1, 1]
Piece-13: [1, 1]
Piece-14: [1, 1]
Piece-15: [1, 1]
Piece-16: [1, 1]
Piece-17: [1, 1]
Piece-18: [1, 1]
Piece-19: [0, 0]
